services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" 
      MYSQL_DATABASE: "${DB_NAME}" 
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql  

  scraper:
    build: .
    container_name: web_scraper
    depends_on:
      - db 
    env_file:
      - .env 
    ports:
      - "8502:8502"
    command: ["wait-for-it", "db:3306", "--", "poetry", "run", "python", "main.py"]

volumes:
  mysql_data:
